check that lzma is installed, time the whole process (8 hours total currently, yikes)

diff --git a/script/update-devel-data/update-devel-data b/script/update-devel-data/update-devel-data
--- a/script/update-devel-data/update-devel-data
+++ b/script/update-devel-data/update-devel-data
@@ -1,3 +1,7 @@
 #!/bin/sh
 
-make -C db create_devel_data
+if ! test -x /usr/bin/lzma; then
+    echo "ERROR: please run sudo apt-get install lzma"
+fi
+
+time make -C db create_devel_data
