use ports 5000+ for socat, I sometimes run a test thin on 3000

diff --git a/script/nice-restart b/script/nice-restart
--- a/script/nice-restart
+++ b/script/nice-restart
@@ -7,10 +7,10 @@ for i in 0 1 2; do
     while [ ! -e /tmp/thin.$i.sock ]; do echo "It doesn't, napping"; sleep 0.5; echo "Checking again"; done
     echo "It does now"
     echo "Starting socat for $i"
-    socat TCP4-LISTEN:300$i,reuseaddr,fork UNIX-CONNECT:/tmp/thin.$i.sock &
+    socat TCP4-LISTEN:500$i,reuseaddr,fork UNIX-CONNECT:/tmp/thin.$i.sock &
     SOCAT=$!
     echo "Trying to download"
-    while ! curl http://localhost:300$i/ 2>/dev/null | grep -q "Free Geek"; do echo "It failed, napping"; sleep 0.5; echo "Checking again"; done
+    while ! curl http://localhost:500$i/ 2>/dev/null | grep -q "Free Geek"; do echo "It failed, napping"; sleep 0.5; echo "Checking again"; done
     echo "It worked"
     echo "Killing socat"
     kill $SOCAT
